version: '2'
services:
    lailife-app:
        image: lailife
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://lailife-mysql:3306/lailife?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=lailife-elasticsearch:9300
        ports:
            - 8080:8080
    lailife-mysql:
        extends:
            file: mysql.yml
            service: lailife-mysql
    lailife-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: lailife-elasticsearch
